# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleActaMunicipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos_provincial', models.IntegerField()),
                ('votos_distrital', models.IntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleActaRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos_pres', models.IntegerField()),
                ('votos_cons', models.IntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDisenioActaMunicipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrital', models.BooleanField(default=False)),
                ('provincial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDisenioActaRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presidente', models.BooleanField(default=False)),
                ('consejero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DisenioActaMunicipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='DisenioActaRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('numero', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('total_electores', models.IntegerField()),
                ('procesada_municipal', models.BooleanField(default=False)),
                ('procesada_regional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VotacionConsejeroRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='VotacionDistrital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Distrito')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='VotacionPresidenteRegional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Region')),
            ],
        ),
        migrations.CreateModel(
            name='VotacionProvincial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='ActaMunicipal',
            fields=[
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='regional.Mesa')),
                ('votos_blancos_prov', models.IntegerField()),
                ('votos_blancos_dis', models.IntegerField()),
                ('votos_nulos_prov', models.IntegerField()),
                ('votos_nulos_dis', models.IntegerField()),
                ('votos_impugnados_prov', models.IntegerField()),
                ('votos_impugnados_dis', models.IntegerField()),
                ('votos_emitidos_prov', models.IntegerField()),
                ('votos_emitidos_dis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActaRegional',
            fields=[
                ('mesa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='regional.Mesa')),
                ('votos_blancos_pres', models.IntegerField()),
                ('votos_nulos_pres', models.IntegerField()),
                ('votos_impugnados_pres', models.IntegerField()),
                ('votos_emitidos_pres', models.IntegerField()),
                ('votos_blancos_cons', models.IntegerField()),
                ('votos_nulos_cons', models.IntegerField()),
                ('votos_impugnados_cons', models.IntegerField()),
                ('votos_emitidos_cons', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='centro_votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.CentroVotacion'),
        ),
        migrations.AddField(
            model_name='detalledisenioactaregional',
            name='disenio_acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.DisenioActaRegional'),
        ),
        migrations.AddField(
            model_name='detalledisenioactaregional',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido'),
        ),
        migrations.AddField(
            model_name='detalledisenioactamunicipal',
            name='disenio_acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.DisenioActaMunicipal'),
        ),
        migrations.AddField(
            model_name='detalledisenioactamunicipal',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localizacion.Partido'),
        ),
        migrations.AddField(
            model_name='detalleactaregional',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.ActaRegional'),
        ),
        migrations.AddField(
            model_name='detalleactamunicipal',
            name='acta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regional.ActaMunicipal'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleactaregional',
            unique_together=set([('acta', 'partido')]),
        ),
        migrations.AlterUniqueTogether(
            name='detalleactamunicipal',
            unique_together=set([('acta', 'partido')]),
        ),
    ]
