# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-19 13:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('modulo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Opcion')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vista',
            unique_together=set([('nombre',)]),
        ),
        migrations.AddField(
            model_name='permisoperfil',
            name='vista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Vista'),
        ),
        migrations.AlterUniqueTogether(
            name='perfil',
            unique_together=set([('nombre',)]),
        ),
        migrations.AddField(
            model_name='opcionperfil',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Perfil'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='vistas',
            field=models.ManyToManyField(to='seguridad.Vista'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioperfil',
            unique_together=set([('usuario', 'perfil')]),
        ),
        migrations.AlterUniqueTogether(
            name='permisoperfil',
            unique_together=set([('perfil', 'vista')]),
        ),
        migrations.AlterUniqueTogether(
            name='opcion',
            unique_together=set([('nombre',)]),
        ),
    ]
